language: php

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - composer install
  - phpunit -c tests/phpunit.xml --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - kenji.uui@gmail.com
